export const AUTHENTICATION = {
    FCM_TOKEN: 'FCM_TOKEN',
    FCM_TOKEN_FAIL: 'FCM_TOKEN_FAIL',
    FCM_TOKEN_SUCCESS: 'FCM_TOKEN_SUCCESS',
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL',
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAIL: 'SIGN_OUT_FAIL',
    SEND_RESET_PASSWORD_LINK: 'SEND_RESET_PASSWORD_LINK',
    SEND_RESET_PASSWORD_LINK_SUCCESS: 'SEND_RESET_PASSWORD_LINK_SUCCESS',
    SEND_RESET_PASSWORD_LINK_FAIL: 'SEND_RESET_PASSWORD_LINK_FAIL',
    RESEND_CONFIRM_EMAIL_LINK: 'RESEND_CONFIRM_EMAIL_LINK',
    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAIL: 'RESET_PASSWORD_FAIL',
    RESEND_UNLOCK_INSTRUCTIONS: 'RESEND_UNLOCK_INSTRUCTIONS',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAIL: 'UPDATE_PROFILE_FAIL',
    DELETE_PROFILE: 'DELETE_PROFILE',
    DELETE_PROFILE_SUCCESS: 'DELETE_PROFILE_SUCCESS',
    DELETE_PROFILE_FAIL: 'DELETE_PROFILE_FAIL',
    UPDATE_HEADERS: 'UPDATE_HEADERS'
};

export const TOPIC = {
    CREATE_TOPIC: 'CREATE_TOPIC',
    CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
    CREATE_TOPIC_FAIL: 'CREATE_TOPIC_FAIL',
    UPDATE_TOPIC: 'UPDATE_TOPIC',
    UPDATE_TOPIC_SUCCESS: 'UPDATE_TOPIC_SUCCESS',
    UPDATE_TOPIC_FAIL: 'UPDATE_TOPIC_FAIL',
    GET_TOPICS: 'GET_TOPICS',
    GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
    GET_TOPICS_FAIL: 'GET_TOPICS_FAIL',
    DELETE_TOPIC: 'DELETE_TOPIC',
    DELETE_TOPIC_SUCCESS: 'DELETE_TOPIC_SUCCESS',
    DELETE_TOPIC_FAIL: 'DELETE_TOPIC_FAIL'
};

export const STUDY = {
    CREATE_STUDY: 'CREATE_STUDY',
    CREATE_STUDY_SUCCESS: 'CREATE_STUDY_SUCCESS',
    CREATE_STUDY_FAIL: 'CREATE_STUDY_FAIL',
    UPDATE_STUDY: 'UPDATE_STUDY',
    UPDATE_STUDY_SUCCESS: 'UPDATE_STUDY_SUCCESS',
    UPDATE_STUDY_FAIL: 'UPDATE_STUDY_FAIL',
    GET_STUDIES: 'GET_STUDIES',
    GET_STUDIES_SUCCESS: 'GET_STUDIES_SUCCESS',
    GET_STUDIES_FAIL: 'GET_STUDIES_FAIL',
    GET_STUDY: 'GET_STUDY',
    GET_STUDY_SUCCESS: 'GET_STUDY_SUCCESS',
    GET_STUDY_FAIL: 'GET_STUDY_FAIL',
    RESET_STUDY: 'RESET_STUDY',
    RESET_STUDY_SUCCESS: 'RESET_STUDY_SUCCESS',
    RESET_STUDY_FAIL: 'RESET_STUDY_FAIL'
};

export const CONTACT = {
    GET_CONTACTS: 'GET_CONTACTS',
    GET_CONTACTS_SUCCESS: 'GET_CONTACTS_SUCCESS',
    GET_CONTACTS_FAIL: 'GET_CONTACTS_FAIL',
    CREATE_CONTACT: 'CREATE_CONTACT',
    CREATE_CONTACT_SUCCESS: 'CREATE_CONTACT_SUCCESS',
    CREATE_CONTACT_FAIL: 'CREATE_CONTACT_FAIL',
    UPDATE_CONTACT: 'UPDATE_CONTACT',
    UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
    UPDATE_CONTACT_FAIL: 'UPDATE_CONTACT_FAIL',
    DELETE_CONTACT: 'DELETE_CONTACT',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS',
    DELETE_CONTACT_FAIL: 'DELETE_CONTACT_FAIL',
    MIRROR_UPDATE_CONTACT_SUCCESS: 'MIRROR_UPDATE_CONTACT_SUCCESS'
};

export const MESSAGE = {
    GET_MESSAGES: 'GET_MESSAGES',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAIL: 'GET_MESSAGES_FAIL',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    CREATE_MESSAGE_SUCCESS: 'CREATE_MESSAGE_SUCCESS',
    CREATE_MESSAGE_FAIL: 'CREATE_MESSAGE_FAIL',
    UPDATE_MESSAGE: 'UPDATE_MESSAGE',
    UPDATE_MESSAGE_SUCCESS: 'UPDATE_MESSAGE_SUCCESS',
    UPDATE_MESSAGE_FAIL: 'UPDATE_MESSAGE_FAIL',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    DELETE_MESSAGE_SUCCESS: 'DELETE_MESSAGE_SUCCESS',
    DELETE_MESSAGE_FAIL: 'DELETE_MESSAGE_FAIL'
};

export const SHARE = {
    CREATE_SHARE: 'CREATE_SHARE',
    CREATE_SHARE_SUCCESS: 'CREATE_SHARE_SUCCESS',
    CREATE_SHARE_FAIL: 'CREATE_SHARE_FAIL',
    DELETE_SHARE: 'DELETE_SHARE',
    DELETE_SHARE_SUCCESS: 'DELETE_SHARE_SUCCESS',
    DELETE_SHARE_FAIL: 'DELETE_SHARE_FAIL'
};

export const COMPARISON = {
    ADD_STUDY: 'ADD_STUDY_TO_COMPARISON_LIST',
    UPDATE_STUDY: 'UPDATE_STUDY_IN_COMPARISON_LIST',
    REMOVE_STUDY: 'REMOVE_STUDY_FROM_COMPARISON_LIST',
    REMOVE_ALL_STUDIES: 'REMOVE_ALL_STUDIES_FROM_COMPARISON_LIST'
};