domain:       <%= Rails.application.credentials[Rails.env.to_sym][:host] %>
website_name: <%= Rails.application.credentials[:website_name] %>
system_email: <%= Rails.application.credentials[:system_email] %>
